GET http://localhost:3000/users


###

POST http://localhost:3000/users/newuser
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###

POST http://localhost:3000/users/subscription
Content-Type: application/json

{
    "_id": "628dbcd10d02d9aa609b68ff"
}

###